### ISSUE TITLE
number of pose doesn't equals to number of rgb-d squences.

### ISSUE THREAD

**Issue by jackchinor** [ethz-asl/autolabel#2]
Nice project. When I run the "python scripts/mapping.py ./my dataset", I found that the number of generated pose doesn't equals to number of rgb-d squences. Do you know the reasons? Thanks

**Comment by kekeblom** [comment]
How many images rgb images do you have going in? How about depth images? Are they numbered consistently such that they match each other? How many poses do you get out?

**Comment by jackchinor** [comment]
number of rgb-d frames is 288，they are keyframes，I only get 282 poses， some keyfames pose lost，and I use computed pose to make a point cloud reconstruction，the result is poor.

**Comment by kekeblom** [comment]
Are they numbered correctly? Which ones are missing? All from the end? Do the missing ones have both an rgb and depth frame associated with them? 

If you can upload the dataset, I can check to see if I can see anything wrong with it.

**Comment by jackchinor** [comment]
Thanks, @kekeblom ,here is my test data which is captured by IPhone 12 pro. https://drive.google.com/file/d/14EFvCPmOrWatiPg5hhTZ4rhWM5N4NslN/view?usp=sharing
Thanks for checking.

**Comment by kekeblom** [comment]
It seems the following frames don't get localized for your scene:
```
01199
01216
01234
01247
01257
```
Which leads to the rgb and depth folders not having corresponding poses for those frames. This then causes some problems down the line with parts of the code assuming the poses are ordered and exist for each rgb and depth image.

This can be circumvented by removing those frames (and any other frames for which a pose is not available) from the resulting `rgb` and `depth` folders.

One fix could be to skip frames that do not have a pose associated with them in `scripts/mapping.py:HLoc._undistort_images` https://github.com/ethz-asl/autolabel/blob/5839a90a233a0d22336a345e1339058f8ae43e97/scripts/mapping.py#L129. 

It does seem like with your dataset, some images do get mislocalized, which is more of a limitation of the underlying structure from motion pipeline and HLoc. In the case of your mobile robot, you might want to use some actual SLAM pipeline that would make use of wheel odometry, potentially inertial information and generally leverage the fact that all images were taken right after each other. 

In general what is important for the structure from motion pipeline is that there are tons of very recognizable overlapping features for each image. Not sure what you want to do with your project, but what you could try, is using more images and with more overlap, for example by using a wider field of view camera that could capture more of the scene simultaneously.

**Comment by jackchinor** [comment]
Thanks for your checking. Actually I want use structure from motion pipeline to generate pose ground truth, then make a evaluation on my own SLAM algorithms. But I found the estimated pose from sfm and HLoc doesn't seems good enough.
